### PR TITLE
Optimizations return accurate datasetId

### PR DESCRIPTION
**Pull request by ylhh353**
1.filter schemaMapInfo !type =VALUE , 

Filtering out data with type=value makes it more useful to select a list of precise data sets
2.DataSetMatchResult.class Increase the number of computations 1.0, and compute similar totals, 
Increase the number of computations for 1.0, and compute the total similarity
3.It is preferred to return datasetId  based on similar total values
Select the one with the largest total similarity value first, then select the one with the largest number of 1.0, and finally calculate the number of types according to it

### CODE REVIEW

**Comment by ylhh353** [comment]
1.filter schemaMapInfo !type =VALUE ,
2.DataSetMatchResult.class Increase the number of computations 1.0, and compute similar totals,

3.It is preferred to return datasetId based on similar total values

**Comment by ylhh353** [comment]
1.filter schemaMapInfo !type =VALUE ,
2.DataSetMatchResult.class Increase the number of computations 1.0, and compute similar totals,

3.It is preferred to return datasetId based on similar total values

**Comment by jerryjzhang** [comment]
这个策略我们之前也讨论过，主要是担心某些数据集存在更多的模糊语义的指标或维度，会导致召回的total similarity变高，但实际上similarity=1.0更多的数据集才是更匹配的

**Comment by jerryjzhang** [comment]
目前感觉更好的顺序是：count(similarity=1.0) > sum(similarity)

**Comment by jerryjzhang** [comment]
基于多个不同用户场景的反馈，已经对规则做了调整，请参考下 #1690

**Pull request closed without merging**
