### PR TITLE
(fix)(chat)Remove spaces when obtaining a MemoryReviewResult

### PR DESCRIPTION
**Pull request by xiuzhu9527**
# Pull Request Template

## Description

LLM response is "opinion=NEGATIVE , comment=日期应该使用date，而不是data_date",  and MemoryReviewResult.valueOf(matcher.group(1)) error

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional information
issues: (https://github.com/tencentmusic/supersonic/issues/1593)
Any additional information, configuration or data that might be necessary to reproduce the issue.

### CODE REVIEW

**Comment by xiuzhu9527** [comment]
@lexluo09 Can you help review this PR? THX!

**Comment by lexluo09** [comment]
Thank you for your contribution. Let's take a look.

**Comment by lexluo09** [comment]
image
您好，提交的代码需要格式化

**Comment by xiuzhu9527** [comment]
@lexluo09 代码已完成格式化

**Comment by jerryjzhang** [comment]
Thank for contributing.

**Pull request merged**
