### PR TITLE
(improvement)(headless) <行级权限过滤条件加到最终执行的sql里>

### PR DESCRIPTION
**Pull request by smlHao**
# Pull Request Template

## Description

加了行级权限表达式，在最终执行的sql里没有包含过滤条件，但是日志里有，debug后，发现最终执行的sql用的是querySqlReq.getSqlInfo().getQuerySQL(),所以在doRowPermission里加上这行代码

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### CODE REVIEW

**Comment by lxwcodemonkey** [comment]
我来处理下

**Comment by jerryjzhang** [comment]
单元测试没有跑通

**Comment by smlHao** [comment]
运行这个单元测试代码报表不存在
image

**Comment by lexluo09** [comment]
你好，可以拉rebase最新代码后，执行mvn spotless:apply格式化代码

**Comment by lexluo09** [comment]
代码应该有问题，不能直接设置成querySQL（物理SQL），会导致真正查询时找不到映射表

**Comment by lexluo09** [comment]
image
设置为setCorrectedS2SQL试试

**Comment by lxwcodemonkey** [comment]
目前看最新代码是可以的

**Pull request closed without merging**
